name: example
description: Example
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter: { sdk: flutter }
  flutter_code_editor: { path: ../ }
  http: ^0.13.5
  highlight:
    git:
      url: https://github.com/yescorp/highlight.dart.git
      ref: 4e75ac3cca4539add6dc53b93bdcb61b9af06fa1
      path: highlight/

dev_dependencies:
  flutter_test: { sdk: flutter }
  total_lints: ^2.17.4

flutter:
  uses-material-design: true
  assets:
    - assets/settings/autoRefactoringSettings.json
