name: example
description: Example
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  code_text_field: { path: ../ }
  flutter: { sdk: flutter }
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0

dev_dependencies:
  flutter_test: { sdk: flutter }
  total_lints: ^2.17.4

flutter:
  uses-material-design: true
  assets:
    - assets/settings/autoRefactoringSettings.json
