name: example
description: Example
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.13.6"

dependencies:
  flutter: { sdk: flutter }
  flutter_code_editor: { path: ../ }
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  http: ^1.1.0

dev_dependencies:
  flutter_test: { sdk: flutter }
  total_lints: ^3.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/settings/autoRefactoringSettings.json
