coverage:
  status:
    project:
      default:
        target: auto
        threshold: 3%
        base: auto
        flags:
          - unit
        paths:
          - "src"
        branches:
          - main
        if_ci_failed: ignore #success, failure, error, ignore
        informational: true
        only_pulls: false
